In [1]:
import numpy as np

basics

In [ ]:
np1 = np.array([0,1,2,3,4,5])
print(np1)

[0 1 2 3 4 5]


In [ ]:
print(np1.shape)

(6,)


In [ ]:
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np3 = np.arange(1,10,2)
print(np3)

[1 3 5 7 9]


In [ ]:
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
np5 = np.zeros((2,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
np6 = np.full((10),6)
print(np6)

[6 6 6 6 6 6 6 6 6 6]


In [ ]:
np7 = np.full((2,10),6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [ ]:
my_list = [2,5,7,9,0]
np8 = np.array(my_list)
print(np8)

[2 5 7 9 0]


In [ ]:
ele = np8[0]
print(ele)

2


Slicing

In [ ]:
npp = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
print(npp[1:3])

[2 3]


In [ ]:
print(npp[2:])

[3 4 5 6 7 8 9]


In [ ]:
print(npp[:])

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(npp[-3:-1])

[7 8]


In [ ]:
print(npp[1:5:2])

[2 4]


In [ ]:
print(npp[::2])

[1 3 5 7 9]


In [ ]:
npp2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
print(npp2[1,2])

8


In [ ]:
print(npp2[0:1,1:3])

[[2 3]]


In [ ]:
print(npp2[0:2,1:3])

[[2 3]
 [7 8]]


Numpy Universal Function

In [ ]:
npp3 = np.array([1,2,3,4,5])

In [ ]:
print(np.sum(npp3))

15


In [ ]:
print(np.sqrt(npp3))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
print(np.absolute(npp3))

[1 2 3 4 5]


In [ ]:
print(np.exp(npp3))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
print(np.max(npp3))
print(np.min(npp3))

5
1


In [ ]:
print(np.sign(npp3))

[1 1 1 1 1]


In [ ]:
print(np.sin(npp3))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
print(np.log(npp3))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


Numpy array copy vs view

In [ ]:
npp4 = np.array([1,2,3,4,5])

create copy

In [ ]:
npp5 = npp4.copy()

create view

In [ ]:
npp6 = npp4.view()

changing elements

In [ ]:
npp4[0]=34

analysing the result

In [ ]:
print(f'original array: {npp4}')
print(f'copy array: {npp5}')
print(f'view array: {npp6}')

original array: [34  2  3  4  5]
copy array: [1 2 3 4 5]
view array: [34  2  3  4  5]


shape and reshape numpy array

In [ ]:
npp7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(npp7)
print(npp7.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
npp8 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(npp8)
print(npp8.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


reshape 1-d to 2-d

In [ ]:
npp9 = npp7.reshape(3,4)
print(npp9)
print(npp9.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


reshape to 3 - d

In [ ]:
npp10 = npp7.reshape(2,3,2)
print(npp10)
print(npp10.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


flatten to 1-d

In [ ]:
npp11 = npp10.reshape(-1)
print(npp11)
print(npp11[-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
12


Iterating through numpy arrays

In [ ]:
npp12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
npp13 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
npp14 = npp12.reshape(2,3,2)

iterating through conventional method

In [ ]:
for x in npp12:
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
for x in npp13:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
for x in npp14:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


better way to do so use "np.nditer"

In [ ]:
for x in np.nditer(npp14):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


Sorting numpy arrays

In [ ]:
npp15 = np.array([6,7,4,9,0,2,1])
npp16 = np.sort(npp15)
print(npp15)
print(npp16)

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]


In [ ]:
npp17 = (["deep","manav","ashish"])
npp18 = np.sort(npp17)
print(npp17)
print(npp18)

['deep', 'manav', 'ashish']
['ashish' 'deep' 'manav']


Searching in numpy array

In [3]:
npp19 = np.array([1,2,3,4,5,3,7,8,9,10])
x = np.where(npp19 == 3)
print(npp19)
print(x[0])

[ 1  2  3  4  5  3  7  8  9 10]
[2 5]


In [4]:
y = np.where(npp19 % 2 == 0)
print(y[0])

[1 3 7 9]


Filtering in numpy array

In [5]:
npp20 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = [True,True,False,False,False,False,False,False,False,False,True,True]
print(npp20)
print(npp20[x])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2 11 12]


In [7]:
filtered = []
for x in npp20:
  if x%2 == 0:
    filtered.append(True)
  else:
    filtered.append(False)

In [8]:
print(npp20[filtered])

[ 2  4  6  8 10 12]


In [9]:
filtered = npp20%2==1
print(npp20[filtered])

[ 1  3  5  7  9 11]
